language: python

# you can use a different version of Python
python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirements.txt

before_script:
   - echo "SECRET_KEY = $ SECRET_KEY" >> .env

# script to run tests. Script can have many commands, one per line.
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py tests

after_script:
  - bash <(curl -s https://codecov.io/bash)